services:
  palworld:
    container_name: palworld
    image: thijsvanloef/palworld-server-docker:latest
    restart: unless-stopped
    ports:
      - '${PALWORLD_GAME_PORT}:${PALWORLD_GAME_PORT}/udp'
      - '${PALWORLD_QUERY_PORT}:${PALWORLD_QUERY_PORT}/udp'
      - '127.0.0.1:${PALWORLD_REST_API_PORT}:${PALWORLD_REST_API_PORT}/tcp'
    volumes:
      - ../../../storage/palworld:/palworld
    environment:
      - PUID=1000
      - PGID=1000
      - PORT=${PALWORLD_GAME_PORT}
      - QUERY_PORT=${PALWORLD_QUERY_PORT}
      - PLAYERS=${PALWORLD_MAX_PLAYERS}
      - TZ=${PALWORLD_TZ}
      - SERVER_NAME=${PALWORLD_SERVER_NAME}
      - SERVER_DESCRIPTION=${PALWORLD_SERVER_DESCRIPTION}
      - ADMIN_PASSWORD=${PALWORLD_ADMIN_PASSWORD}
      - DIFFICULTY=${PALWORLD_DIFFICULTY}
      - COMMUNITY=${PALWORLD_COMMUNITY}
      - UPDATE_ON_BOOT=true
      - REST_API_ENABLED=true
      - REST_API_PORT=${PALWORLD_REST_API_PORT}
      - ENABLE_PLAYER_LOGGING=${PALWORLD_ENABLE_PLAYER_LOGGING}
      - DISCORD_WEBHOOK_URL=${PALWORLD_DISCORD_WEBHOOK_URL}
      - ENABLE_PERF_THREADING_ARGS=${PALWORLD_ENABLE_PERF_THREADING_ARGS}
      - WORKER_THREADS_SERVER=${PALWORLD_WORKER_THREADS_SERVER}
      - AUTO_PAUSE_ENABLED=${PALWORLD_AUTO_PAUSE_ENABLED}
      - AUTO_UPDATE_ENABLED=${PALWORLD_AUTO_UPDATE_ENABLED}
      - "AUTO_UPDATE_CRON_EXPRESSION=0 5 * * *"
      - AUTO_UPDATE_WARN_MINUTES=${PALWORLD_AUTO_UPDATE_WARN_MINUTES}
      - AUTO_REBOOT_ENABLED=${PALWORLD_AUTO_REBOOT_ENABLED}
      - "AUTO_REBOOT_CRON_EXPRESSION=0 3 * * *"
      - AUTO_REBOOT_WARN_MINUTES=${PALWORLD_AUTO_REBOOT_WARN_MINUTES}
      - AUTO_REBOOT_EVEN_IF_PLAYERS_ONLINE=${PALWORLD_AUTO_REBOOT_EVEN_IF_PLAYERS_ONLINE}
      - BACKUP_ENABLED=true
      - DELETE_OLD_BACKUPS=true
      - OLD_BACKUP_DAYS=7
    networks:
      - lab
    deploy:
      resources:
        limits:
          cpus: '8.0'
          memory: 6G
        reservations:
          cpus: '2.0'
          memory: 2G

networks:
  lab:
    name: lab
    external: true
