services:
  portainer:
    container_name: portainer
    image: portainer/portainer-ce:latest
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ../../../storage/portainer:/data
    ports:
      - ${PORTAINER_PORT}:9000