services:
  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    restart: unless-stopped
    command: 'tunnel --no-autoupdate run --token ${CLOUDFLARE_TUNNEL_TOKEN}'
    networks:
      - lab
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 64M

networks:
  lab:
    name: lab
    external: true