include:
    - ./cloudflared/compose.yml
    - ./dozzle/compose.yml
    - ./filebrowser/compose.yml
    - ./glances/compose.yml
    - ./nginx/compose.yml
    - ./ofelia/compose.yml
    - ./rclone/compose.yml
    - ./restic/compose.yml
