services:
  ngrok:
    image: ngrok/ngrok:latest
    container_name: ngrok
    restart: unless-stopped
    command: 'http --url=${NGROK_DOMAIN} nginx:80'
    environment:
      - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN}
    networks:
      - backup

networks:
  backup:
    name: backup
    external: true