services:
  btop:
    container_name: btop
    restart: unless-stopped
    build: ../../../docker/btop
    tty: true
    stdin_open: true
    pid: "host"
    ports:
      - "${BTOP_PORT}:7681"
    volumes:
      - /proc:/proc:ro
      - /sys:/sys:ro
      - /:/host:ro
    networks:
      - lab
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 64M

networks:
  lab:
    name: lab
    external: true
