services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    environment:
      - NGINX_DOZZLE_DOMAIN=${NGINX_DOZZLE_DOMAIN}
      - NGINX_DOZZLE_PORT=${NGINX_DOZZLE_PORT}
      - NGINX_YTDLP_DOMAIN=${NGINX_YTDLP_DOMAIN}
      - NGINX_YTDLP_PORT=${NGINX_YTDLP_PORT}
    volumes:
      - ./configuration/nginx.conf.template:/etc/nginx/templates/nginx.conf.template:ro
    networks:
      - lab
networks:
  lab:
    name: lab
    external: true