services:
  satisfactory:
    container_name: 'satisfactory'
    image: 'wolveix/satisfactory-server:latest'
    restart: unless-stopped
    ports:
      - '${SATISFACTORY_GAME_PORT}:${SATISFACTORY_GAME_PORT}/tcp'
      - '${SATISFACTORY_GAME_PORT}:${SATISFACTORY_GAME_PORT}/udp'
      - '${SATISFACTORY_MESSAGING_PORT}:${SATISFACTORY_MESSAGING_PORT}/tcp'
    volumes:
      - ../../../storage/satisfactory:/config
    environment:
      - MAXPLAYERS=${SATISFACTORY_MAX_PLAYERS}
      - SERVERGAMEPORT=${SATISFACTORY_GAME_PORT}
      - SERVERMESSAGINGPORT=${SATISFACTORY_MESSAGING_PORT}
      - PGID=1000
      - PUID=1000
      - STEAMBETA=false
    deploy:
      resources:
        limits:
          memory: 12G
        reservations:
          memory: 6G