services:
  satisfactory:
    container_name: 'satisfactory'
    image: 'wolveix/satisfactory-server:latest'
    restart: unless-stopped
    ports:
      - '${SATISFACTORY_GAME_PORT}:${SATISFACTORY_GAME_PORT}/tcp'
      - '${SATISFACTORY_GAME_PORT}:${SATISFACTORY_GAME_PORT}/udp'
      - '${SATISFACTORY_MESSAGING_PORT}:${SATISFACTORY_MESSAGING_PORT}/tcp'
    volumes:
      - ../../../storage/satisfactory:/config
    environment:
      - MAXPLAYERS=${SATISFACTORY_MAX_PLAYERS}
      - SERVERGAMEPORT=${SATISFACTORY_GAME_PORT}
      - SERVERMESSAGINGPORT=${SATISFACTORY_MESSAGING_PORT
      - AUTOSAVENUM={SATISFACTORY_AUTO_SAVE_FILES}
      - PGID=1000
      - PUID=1000
      - STEAMBETA=false
    networks:
      - lab
    deploy:
      resources:
        limits:
          cpus: '8.0'
          memory: 12G
        reservations:
          cpus: '2.0'
          memory: 6G

networks:
  lab:
    name: lab
    external: true
