services:
  restic-satisfactory:
    image: restic/restic:latest
    container_name: restic-satisfactory
    restart: unless-stopped
    entrypoint: /bin/sh
    command: '-c "tail -f /dev/null"'
    environment:
      - RESTIC_REPOSITORY=rest:http://rclone:${RESTIC_RCLONE_SERVER_PORT}/satisfactory/
      - RESTIC_PASSWORD=${RESTIC_SATISFACTORY_PASSWORD}
    volumes:
      - ../../../storage/satisfactory/saved:/data:ro
    networks:
      - lab
    labels:
      ofelia.enabled: "true"
      ofelia.job-exec.backup-satisfactory.schedule: "@every 20m"
      ofelia.job-exec.backup-satisfactory.command: "restic backup /data"
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 256M

  restic-palworld:
    image: restic/restic:latest
    container_name: restic-palworld
    restart: unless-stopped
    entrypoint: /bin/sh
    command: '-c "tail -f /dev/null"'
    environment:
      - RESTIC_REPOSITORY=rest:http://rclone:${RESTIC_RCLONE_SERVER_PORT}/palworld/
      - RESTIC_PASSWORD=${RESTIC_PALWORLD_PASSWORD}
    volumes:
      - ../../../storage/palworld/Pal/Saved/SaveGames:/data:ro
    networks:
      - lab
    labels:
      ofelia.enabled: "true"
      ofelia.job-exec.backup-palworld.schedule: "@every 20m"
      ofelia.job-exec.backup-palworld.command: "restic backup /data"
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 256M

  restic-wakapi:
    image: restic/restic:latest
    container_name: restic-wakapi
    restart: unless-stopped
    entrypoint: /bin/sh
    command: '-c "tail -f /dev/null"'
    environment:
      - RESTIC_REPOSITORY=rest:http://rclone:${RESTIC_RCLONE_SERVER_PORT}/wakapi/
      - RESTIC_PASSWORD=${RESTIC_WAKAPI_PASSWORD}
    volumes:
      - ../../../storage/wakapi/data:/data:ro
    networks:
      - lab
    labels:
      ofelia.enabled: "true"
      ofelia.job-exec.backup-wakapi.schedule: "@every 20m"
      ofelia.job-exec.backup-wakapi.command: "restic backup /data"
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 256M

  restic-hermes:
    image: restic/restic:latest
    container_name: restic-hermes
    restart: unless-stopped
    entrypoint: /bin/sh
    command: '-c "tail -f /dev/null"'
    environment:
      - RESTIC_REPOSITORY=rest:http://rclone:${RESTIC_RCLONE_SERVER_PORT}/hermes/
      - RESTIC_PASSWORD=${RESTIC_HERMES_PASSWORD}
    volumes:
      - ../../../storage/hermes/data:/data:ro
      - ./configuration/hermes-include.txt:/etc/restic/hermes-include.txt:ro
    networks:
      - lab
    labels:
      ofelia.enabled: "true"
      ofelia.job-exec.backup-hermes.schedule: "@every 6h"
      ofelia.job-exec.backup-hermes.command: "restic backup --files-from /etc/restic/hermes-include.txt"
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 256M

networks:
  lab:
    name: lab
    external: true