include:
    - ./hermes/compose.yml
    - ./kamiyomu/compose.yml
    - ./kavita/compose.yml
    - ./ytdlp/compose.yml
    - ./satisfactory/compose.yml
    - ./palworld/compose.yml
    - ./teamspeak/compose.yml
    # - ./dst/compose.yml  # not configured yet, see services/apps/dst/.env.example
